language: go
sudo: false
notifications:
  email: false
jobs:
  include:
    - stage: test
      go_import_path: github.com/golang/dep
      install:
        - make get-deps
        - npm install -g codeclimate-test-reporter
      env:
        - DEPTESTBYPASS501=1
      os: linux
      go: 1.10.x
      script:
        - make validate test
        - ./hack/coverage.bash
      after_success:
        - codeclimate-test-reporter < coverage.txt
    # YAML alias, for settings shared across the simpler builds
    - &simple-test
      go: 1.9.x
      stage: test
      go_import_path: github.com/golang/dep
      install: skip
      env:
        - DEPTESTBYPASS501=1
      script: make test
    - <<: *simple-test
      go: tip
    - <<: *simple-test
      os: linux-ppc64le
      go: 1.10.x
      script:
        - make validate test
        - ./hack/coverage.bash
      after_success:
        - codeclimate-test-reporter < coverage.txt
    # YAML alias, for settings shared across the simpler builds
    - &simple-test
      go: 1.9.x
      stage: test
      go_import_path: github.com/golang/dep
      install: skip
      env:
        - DEPTESTBYPASS501=1
      script: make test
    - <<: *simple-test
      go: tip
    - <<: *simple-test
      os: osx
      go: 1.10.x
      install:
        # brew takes horribly long to update itself despite the above caching
        # attempt; only bzr install if it's not on the $PATH
        - test $(which bzr) || brew install bzr
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - DEPTESTBYPASS501=1
      script:
        # OSX as of El Capitan sets an exit trap that interacts poorly with how
        # travis seems to spawn these shells; if set -e is set, then it can cause
        # build failures. We're not doing that here, but retain the trap statement
        # for future safety.
        # Related: https://superuser.com/questions/1044130/why-am-i-having-how-can-i-fix-this-error-shell-session-update-command-not-f
        - trap EXIT
        - make test
    - go: 1.10.x
      # Run on OS X so that we get a CGO-enabled binary for this OS; see
      # https://github.com/golang/dep/issues/1838 for more details.
      os: osx
      stage: deploy
      go_import_path: github.com/golang/dep
      install: skip
      script: skip
      before_deploy:
        - ./hack/build-all.bash
        
